In [1]:
import pandas as pd

EPIWEEK = '202614'

In [2]:
multi_prop = pd.read_csv(f'../flu-forecast-epydemix/common-data/surveillance/{EPIWEEK}_multistrain_proportions.csv')

In [3]:
ed = pd.read_csv(f'../flu-forecast-epydemix/common-data/surveillance/flu_prop-ed_25_{EPIWEEK}_scaled.csv')

In [4]:
metro = pd.read_csv(f'../flu-forecast-epydemix/common-data/surveillance/metrocast_{EPIWEEK}_scaled.csv')

In [4]:
hosp = pd.read_csv(f'../flu-forecast-epydemix/common-data/surveillance/flu_hosp_25_{EPIWEEK}_prelim.csv')

## Hosp

In [37]:
us_multi_h1, us_multi_h3, us_multi_b, us_multi_total = [], [], [], []

In [38]:
hosp_multi = hosp.merge(multi_prop,
                        left_on=['target_end_date', 'location_code', 'location_iso', 'epiweek'],
                        right_on=['target_end_date', 'location_code', 'location_iso', 'epiweek'],
                        how='left').drop(columns=['abbreviation']).rename(columns={'target_end_date':'date','hospitalizations':'value','location_code':'location'})

In [39]:
hosp_multi['value_H1'] = hosp_multi.value * hosp_multi.prop_H1
hosp_multi['value_H3'] = hosp_multi.value * hosp_multi.prop_H3
hosp_multi['value_B'] = hosp_multi.value * hosp_multi.prop_B

In [40]:
us_hosp_multi = hosp_multi[hosp_multi.location == 'US']
hosp_multi = hosp_multi[hosp_multi.location != 'US']

In [41]:
for row in us_hosp_multi.itertuples():
    h1 = hosp_multi[hosp_multi.date == row.date].value_H1.sum()
    h3 = hosp_multi[hosp_multi.date == row.date].value_H3.sum()
    b = hosp_multi[hosp_multi.date == row.date].value_B.sum()
    us_multi_h1.append(h1)
    us_multi_h3.append(h3)
    us_multi_b.append(b)

In [42]:
us_hosp_multi.value_H1 = us_multi_h1
us_hosp_multi.value_H3 = us_multi_h3
us_hosp_multi.value_B = us_multi_b

In [43]:
hosp_multi = pd.concat([hosp_multi, us_hosp_multi])

In [44]:
hosp_multi

,location_iso,location,date,epiweek,value,prop_H1,prop_H3,prop_B,total,value_H1,value_H3,value_B
0,US-AL,01,2024-01-06,202401,348.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,US-AL,01,2024-01-13,202402,226.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,US-AL,01,2024-01-20,202403,169.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,US-AL,01,2024-01-27,202404,140.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,US-AL,01,2024-02-03,202405,103.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
6027,US,US,2026-02-21,202607,14593.0,NaN,NaN,NaN,NaN,1507.657960,6454.562339,6452.779702
6028,US,US,2026-02-28,202608,11008.0,NaN,NaN,NaN,NaN,1152.737104,3776.233538,5969.029357
6029,US,US,2026-03-07,202609,9508.0,NaN,NaN,NaN,NaN,779.785287,2775.726709,5861.488004
6030,US,US,2026-03-14,202610,7614.0,NaN,NaN,NaN,NaN,540.832679,1715.102256,5234.065065
6031,US,US,2026-03-21,202611,5408.0,NaN,NaN,NaN,NaN,374.094127,1200.880274,3686.025598

In [ ]:
hosp_multi.to_csv(f'../flu-forecast-epydemix/common-data/surveillance/flu_hosp_25_{EPIWEEK}_prelim_multi.csv', index=False)

## ED

In [5]:
us_multi_h1, us_multi_h3, us_multi_b, us_multi_total = [], [], [], []

In [6]:
ed_multi = ed.merge(multi_prop,
                    left_on=['date', 'location', 'location_iso'],
                    right_on=['target_end_date', 'location_code', 'location_iso'],
                    how='left').drop(columns=['location_code','target_end_date','abbreviation'])

In [7]:
ed_multi['value_H1'] = ed_multi.value * ed_multi.prop_H1
ed_multi['value_H3'] = ed_multi.value * ed_multi.prop_H3
ed_multi['value_B'] = ed_multi.value * ed_multi.prop_B

In [8]:
us_ed_multi = ed_multi[ed_multi.location == 'US']
ed_multi = ed_multi[ed_multi.location != 'US']

In [9]:
for row in us_ed_multi.itertuples():
    h1 = ed_multi[ed_multi.date == row.date].value_H1.sum()
    h3 = ed_multi[ed_multi.date == row.date].value_H3.sum()
    b = ed_multi[ed_multi.date == row.date].value_B.sum()
    us_multi_h1.append(h1)
    us_multi_h3.append(h3)
    us_multi_b.append(b)

In [10]:
us_ed_multi.value_H1 = us_multi_h1
us_ed_multi.value_H3 = us_multi_h3
us_ed_multi.value_B = us_multi_b

In [11]:
ed_multi = pd.concat([ed_multi, us_ed_multi])

In [12]:
ed_multi

,date,location_name,value,original_value,location,location_iso,epiweek,prop_H1,prop_H3,prop_B,total,value_H1,value_H3,value_B
0,2022-10-01,Alabama,64.366697,0.0126,01,US-AL,202239,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022-10-08,Alabama,119.538151,0.0234,01,US-AL,202240,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2022-10-15,Alabama,190.545856,0.0373,01,US-AL,202241,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2022-10-22,Alabama,307.018927,0.0601,01,US-AL,202242,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2022-10-29,Alabama,596.669062,0.1168,01,US-AL,202243,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9379,2026-03-07,US,8385.390533,0.0248,US,US,202609,NaN,NaN,NaN,NaN,607.115213,2258.108932,4978.982989
9380,2026-03-14,US,6694.787603,0.0198,US,US,202610,NaN,NaN,NaN,NaN,603.346542,1409.330326,4329.013688
9381,2026-03-21,US,5274.681142,0.0156,US,US,202611,NaN,NaN,NaN,NaN,664.202205,844.765755,3611.705658
9382,2026-03-28,US,4530.815852,0.0134,US,US,202612,NaN,NaN,NaN,NaN,537.827394,692.285365,3148.822380
9383,2026-04-04,US,3584.078212,0.0106,US,US,202613,NaN,NaN,NaN,NaN,415.007644,547.371317,2481.217458

In [13]:
ed_multi.to_csv(f'../flu-forecast-epydemix/common-data/surveillance/flu_prop-ed_25_{EPIWEEK}_scaled_multi.csv', index=False)

## Metro

In [14]:
metro_loc = pd.read_csv('../experiments/multistrain/proportions/metro_locations.csv')

In [15]:
metro = metro.merge(metro_loc,
                    left_on=['location'],
                    right_on=['location'],
                    how='left').drop(columns=['original_location_code','state','location_name','population','location_type','hsa_counties'])

In [16]:
metro_multi = metro.merge(multi_prop,
                          left_on=['date', 'state_abb'],
                          right_on=['target_end_date','abbreviation'],
                          how='left').drop(columns=['state_abb','location_iso','location_code','target_end_date','abbreviation'])

In [17]:
metro_multi['value_H1'] = metro_multi.value * metro_multi.prop_H1
metro_multi['value_H3'] = metro_multi.value * metro_multi.prop_H3
metro_multi['value_B'] = metro_multi.value * metro_multi.prop_B

In [18]:
metro_multi

,date,value,original_value,location,epiweek,prop_H1,prop_H3,prop_B,total,value_H1,value_H3,value_B
0,2022-10-01,1.736154,0.45,athens,202239.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022-10-08,3.047915,0.79,athens,202240.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2022-10-15,4.938394,1.28,athens,202241.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2022-10-22,8.950838,2.32,athens,202242.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2022-10-29,22.955814,5.95,athens,202243.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
19708,2026-03-07,11.843842,1.27,worcester,202609.0,0.115385,0.153846,0.730769,1.0,1.366597,1.822130,8.655115
19709,2026-03-14,14.455083,1.55,worcester,202610.0,0.096774,0.161290,0.741935,1.0,1.398879,2.331465,10.724739
19710,2026-03-21,15.294410,1.64,worcester,202611.0,0.030303,0.090909,0.878788,1.0,0.463467,1.390401,13.440542
19711,2026-03-28,19.864082,2.13,worcester,202612.0,0.030303,0.090909,0.878788,1.0,0.601942,1.805826,17.456314
19712,2026-04-04,16.133738,1.73,worcester,202613.0,0.030303,0.090909,0.878788,1.0,0.488901,1.466703,14.178133

In [19]:
metro_multi.to_csv(f'../flu-forecast-epydemix/common-data/surveillance/metrocast_{EPIWEEK}_scaled_multi.csv', index=False)